### ISSUE TITLE
TRACI toxicity characterization factors missing for flows without secondary context

### ISSUE THREAD

**Issue by bl-young** [USEPA/LCIAformatter#4]
The underlying TRACI characterization factors specify secondary context for toxicity impacts (e.g. air/rural or air/urban). However many users may not have the data to specify a secondary context and will use emission/air resulting in no toxicity impacts.

It may be worth considering an approach to estimate impacts for unspecified secondary context (like an average) or being clear in the metadata that flows lacking a secondary context will not have toxicity impacts.

**Comment by WesIngwersen** [comment]
It's definitely better to apply characterization. I am OK with an average of rural and urban factors which may be a common resolution of this issue. I will consult the TRACI team.

**Comment by WesIngwersen** [comment]
I added a calculation of average factors for primary contexts as the default option for TRACI 2.1. Note this will overwrite as applied any existing factors that just apply to the primary contexts, but this is not the case I don't believe for TRACI 2.1.  This however does not solve all TRACI 2.1 issues because important mappings are missing in fedelemflowlist.
